### ISSUE TITLE
Cannot start scales

### ISSUE THREAD

**Issue by Blackbird1604** [PufferPanel/Scales#11]
Hi, cannot start scales
This is the Output in Verbose Mode

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /srv/scales/node_modules/pty.js/build/Release/pty.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/scales/node_modules/pty.js/lib/pty.js:8:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Blackbird1604** [comment]
Ok now i can start it but in pufferpannel i cant create any servers

**Comment by DaneEveritt** [comment]
So Scales is starting correctly and not displaying any errors? Can you access `https://iptoscales.tld:5656/` in your browser?

Please provide the relevant logs from PufferPanel which can be found in `src/logs/info.log`.

**Comment by Blackbird1604** [comment]
Yep i can acess it via the IP and the Port in my browser.
The Info Log doesnt exist on my System.

**Comment by DaneEveritt** [comment]
Please make an issue on the PufferPanel issue tracker since it is an issue with the panel and not Scales.
