### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by Thunderbird2** [PufferPanel/Scales#14]
Here is the error:

[12:59:55][INFO] + ========================================== +
[12:59:55][INFO] | Scales logs all information, (inc. errors) |
[12:59:55][INFO] | into the logs/ directory. Please check     |
[12:59:55][INFO] | there before asking for help with bugs.    |
[12:59:55][INFO] |                                            |
[12:59:55][INFO] | Submit bug reports at the following link:  |
[12:59:55][INFO] | https://github.com/PufferPanel/Scales      |
[12:59:55][INFO] + ========================================== +
module.js:338
    throw err;
          ^
Error: Cannot find module '../../config.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/scales/lib/interfaces/restify.js:6:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by Thunderbird2** [comment]
Also I cannot start my server when doing: 
cd /srv/gsd
npm start

This error appears:

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/gsd/node_modules/pty.js/lib/pty.js:8:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! GameServerDaemon@0.1.4 start: `node gsd.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the GameServerDaemon@0.1.4 start script 'node gsd.js'.
npm ERR! This is most likely a problem with the GameServerDaemon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node gsd.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls GameServerDaemon
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/gsd/npm-debug.log

**Comment by puffrfish** [comment]
For Scales, is there a config.json file in the /srv/scales directory? If not, please create one with the contents of what the panel generates for you.

**Comment by DaneEveritt** [comment]
You did not follow the documentation for installing Scales with PufferPanel. You must create the node within PufferPanel before installing Scales so that you have the `config.json` file to input.
