### ISSUE TITLE
Problem starting scales!

### ISSUE THREAD

**Issue by DDynamic** [PufferPanel/Scales#23]
Hello,
Using the latest dev build of scales fails to start with this error.

```
[19:15:40][VERBOSE] Scales running in verbose mode.
[19:15:40][INFO] + ========================================== +
[19:15:40][INFO] | Scales logs all information, (inc. errors) |
[19:15:40][INFO] | into the logs/ directory. Please check     |
[19:15:40][INFO] | there before asking for help with bugs.    |
[19:15:40][INFO] |                                            |
[19:15:40][INFO] | Submit bug reports at the following link:  |
[19:15:40][INFO] | https://github.com/PufferPanel/Scales      |
[19:15:40][INFO] + ========================================== +
[19:15:40][INFO] Loading plugin bungeecord.js...
[19:15:40][INFO] Loading plugin mcserver.js...
module.js:338
    throw err;
          ^
Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/scales/lib/plugins/mcserver.js:12:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Reverting commit `c044cd6696c54c4f425b41737a63965ae999f471` seems to fix this problem. Might want to check this :).

**Comment by Omeryl** [comment]
Why do I have a feeling that `npm install` would fix this? See https://github.com/PufferPanel/Scales/blob/c044cd6696c54c4f425b41737a63965ae999f471/package.json#L33. This is a problem that exists between computer and chair.

**Comment by DDynamic** [comment]
That fixed everything. Sorry I'm an idiot. xD

**Comment by Omeryl** [comment]
Just, some common sense and actually reading the error would help a bit! Enjoy.
