### ISSUE TITLE
Scales not creating servers

### ISSUE THREAD

**Issue by the-mann** [PufferPanel/Scales#54]
Whenever I try to create an error, my scales log shows this:

[2015-10-30 06:47:46] [VERBOSE] Creating user pp-plswor_kj0sb on the server.
[2015-10-30 06:47:47] [VERBOSE] Finished basic install process for new server, preparing to complete full install process.
[2015-10-30 06:47:47] [VERBOSE] Attempting to gather user information to create a container for server 7e80efec-083a-4d4f-b634-2a32f1632fc3
[2015-10-30 06:47:47] [VERBOSE] Creating docker container for server 7e80efec-083a-4d4f-b634-2a32f1632fc3
[2015-10-30 06:47:47] [ERROR] Unable to complete the installer process. Hanging server until this is looked at...
Error: docker create command exited with non-zero error code [1].
    at Socket.<anonymous> (/srv/scales/lib/process.js:325:37)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at Terminal.emit (/srv/scales/node_modules/pty.js/lib/pty.js:306:27)
    at onexit (/srv/scales/node_modules/pty.js/lib/pty.js:118:10)

**Comment by DaneEveritt** [comment]
You've been warned multiple times to stop, creating alternate accounts to evade bans is not a good way to get help from this community. If you wanted to get support, then you should have heeded our warnings to stop acting like a child.
