### ISSUE TITLE
Scales error

### ISSUE THREAD

**Issue by Thunderbird2** [PufferPanel/Scales#7]
Hi I have tried to install scales and I encountered this error:

npm ERR! Scales@0.1.0 start: `node lib/scales.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the Scales@0.1.0 start script.
npm ERR! This is most likely a problem with the Scales package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/scales.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls Scales
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /srv/scales
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/scales/npm-debug.log
npm ERR! not ok code 0
root@DominantCraft-0:/srv/scales# node lib/scales.js verbose
[22:44:36][VERBOSE] Scales running in verbose mode.
[22:44:36][INFO] + ========================================== +
[22:44:36][INFO] | Scales logs all information, (inc. errors) |
[22:44:36][INFO] | into the logs/ directory. Please check     |
[22:44:36][INFO] | there before asking for help with bugs.    |
[22:44:36][INFO] |                                            |
[22:44:36][INFO] | Submit bug reports at the following link:  |
[22:44:36][INFO] | https://github.com/PufferPanel/Scales      |
[22:44:36][INFO] + ========================================== +

module.js:340
    throw err;
          ^
Error: Cannot find module '../../config.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/scales/lib/interfaces/restify.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by LordRalex** [comment]
You have to create the config.json after setting the node up through the panel.
