### ISSUE TITLE
New server installation error

### ISSUE THREAD

**Issue by Tehtafara0** [PufferPanel/Scales#75]
When i'm creating a new server the installation process doesn't outputs something and i found this in the logs:
[2016-02-05 16:06:03] [VERBOSE] Executing cmd: docker create -it --name pp-1337_hz4qkfg -h docker -m 1024M --blkio-weight=500 --cpu-period=100000 --cpu-quota=100000 -p 0.0.0.0:25579:25579 -p 0.0.0.0:25579:25579/udp -u 1000 -v /home/pp-1337_hz4qkfg/public:/home/container pufferpanel/minecraft:latest
[2016-02-05 16:06:03] [ERROR] Unable to complete the installer process. Please check the logs for more information.
Error: docker create command exited with non-zero error code [1].
    at Socket.<anonymous> (/srv/scales/lib/controller/system.js:175:41)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at Terminal.emit (/srv/scales/node_modules/pty.js/lib/pty.js:306:27)
    at onexit (/srv/scales/node_modules/pty.js/lib/pty.js:118:10)

**Comment by LordRalex** [comment]
Is docker running?

**Comment by Tehtafara0** [comment]
docker?

**Comment by LordRalex** [comment]
The fact you asked that says probably not.

service docker start

**Comment by Tehtafara0** [comment]
I checked the checkbox to don't use docker. It's now working fine. Thank you :)
