### ISSUE TITLE
I killed it.

### ISSUE THREAD

**Issue by SysVoid** [PufferPanel/Scales#77]
```
> ./scales start

Using system node
Starting Scales
[2016-03-01 03:13:19] [INFO] + ========================================== +
[2016-03-01 03:13:19] [INFO] | Scales logs all information, (inc. errors) |
[2016-03-01 03:13:19] [INFO] | into the logs/ directory. Please check     |
[2016-03-01 03:13:19] [INFO] | there before asking for help with bugs.    |
[2016-03-01 03:13:19] [INFO] |                                            |
[2016-03-01 03:13:19] [INFO] | Submit bug reports at the following link:  |
[2016-03-01 03:13:19] [INFO] | https://github.com/PufferPanel/Scales      |
[2016-03-01 03:13:19] [INFO] + ========================================== +
[2016-03-01 03:13:19] [ERROR] uncaughtException: Object #<Object> has no method 'execSync'
[2016-03-01 03:13:19] [ERROR] Unhandled exception occurred
TypeError: Object #<Object> has no method 'execSync'
    at Object.<anonymous> (/srv/scales/index.js:28:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

```

**Comment by LordRalex** [comment]
Was this an update of Scales or a fresh install?

**Comment by SysVoid** [comment]
Update

**Comment by LordRalex** [comment]
How did you update it?

**Comment by SysVoid** [comment]
copy/paste commands from Scales update documentation as listed on the site

**Comment by LordRalex** [comment]
Do the following command, and provide the output:

./scales node_install

**Comment by SysVoid** [comment]
```
[root@srv1 scales]# ./scales node_install
Using system node
Loaded plugins: fastestmirror, presto
Setting up Install Process
Determining fastest mirrors
epel/metalink                                            |  25 kB     00:00
 * epel: mirror.imt-systems.com
 * remi-safe: rpms.remirepo.net
base                                                     | 3.7 kB     00:00
docker-main-repo                                         | 2.9 kB     00:00
epel                                                     | 4.3 kB     00:00
epel/primary_db                                          | 5.8 MB     00:00
extras                                                   | 3.4 kB     00:00
extras/primary_db                                        |  34 kB     00:00
mongodb                                                  |  951 B     00:00
nodesource                                               | 2.5 kB     00:00
nodesource/primary_db                                    |  20 kB     00:00
remi-safe                                                | 2.9 kB     00:00
remi-safe/primary_db                                     | 242 kB     00:00
updates                                                  | 3.4 kB     00:00
updates/primary_db                                       | 3.9 MB     00:00
Package curl-7.19.7-46.el6.x86_64 already installed and latest version
Package 1:make-3.81-20.el6.x86_64 already installed and latest version
Package gcc-4.4.7-16.el6.x86_64 already installed and latest version
Package gcc-c++-4.4.7-16.el6.x86_64 already installed and latest version
Package 2:tar-1.23-13.el6.x86_64 already installed and latest version
Package 2:tar-1.23-13.el6.x86_64 already installed and latest version
Package python-2.6.6-64.el6.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package glibc.i686 0:2.12-1.166.el6_7.3 will be updated
---> Package glibc.i686 0:2.12-1.166.el6_7.7 will be an update
--> Processing Dependency: glibc-common = 2.12-1.166.el6_7.7 for package: glibc-                                                2.12-1.166.el6_7.7.i686
---> Package java-1.8.0-openjdk-devel.x86_64 1:1.8.0.71-1.b15.el6_7 will be inst                                                alled
--> Processing Dependency: java-1.8.0-openjdk = 1:1.8.0.71-1.b15.el6_7 for packa                                                ge: 1:java-1.8.0-openjdk-devel-1.8.0.71-1.b15.el6_7.x86_64
--> Processing Dependency: libawt_xawt.so(SUNWprivate_1.1)(64bit) for package: 1                                                :java-1.8.0-openjdk-devel-1.8.0.71-1.b15.el6_7.x86_64
--> Processing Dependency: libawt_xawt.so()(64bit) for package: 1:java-1.8.0-ope                                                njdk-devel-1.8.0.71-1.b15.el6_7.x86_64
---> Package libstdc++.i686 0:4.4.7-16.el6 will be installed
--> Processing Dependency: libgcc_s.so.1(GLIBC_2.0) for package: libstdc++-4.4.7                                                -16.el6.i686
--> Processing Dependency: libgcc_s.so.1(GCC_4.2.0) for package: libstdc++-4.4.7                                                -16.el6.i686
--> Processing Dependency: libgcc_s.so.1(GCC_3.3) for package: libstdc++-4.4.7-1                                                6.el6.i686
--> Processing Dependency: libgcc_s.so.1(GCC_3.0) for package: libstdc++-4.4.7-1                                                6.el6.i686
--> Processing Dependency: libgcc_s.so.1 for package: libstdc++-4.4.7-16.el6.i68                                                6
---> Package openssl.x86_64 0:1.0.1e-42.el6_7.1 will be updated
---> Package openssl.x86_64 0:1.0.1e-42.el6_7.4 will be an update
--> Running transaction check
---> Package glibc-common.x86_64 0:2.12-1.166.el6_7.3 will be updated
--> Processing Dependency: glibc-common = 2.12-1.166.el6_7.3 for package: glibc-                                                2.12-1.166.el6_7.3.x86_64
---> Package glibc-common.x86_64 0:2.12-1.166.el6_7.7 will be an update
---> Package java-1.8.0-openjdk.x86_64 1:1.8.0.71-1.b15.el6_7 will be installed
--> Processing Dependency: java-1.8.0-openjdk-headless = 1:1.8.0.71-1.b15.el6_7                                                 for package: 1:java-1.8.0-openjdk-1.8.0.71-1.b15.el6_7.x86_64
---> Package libgcc.i686 0:4.4.7-16.el6 will be installed
--> Running transaction check
---> Package glibc.x86_64 0:2.12-1.166.el6_7.3 will be updated
--> Processing Dependency: glibc = 2.12-1.166.el6_7.3 for package: glibc-devel-2                                                .12-1.166.el6_7.3.x86_64
--> Processing Dependency: glibc = 2.12-1.166.el6_7.3 for package: glibc-headers                                                -2.12-1.166.el6_7.3.x86_64
---> Package glibc.x86_64 0:2.12-1.166.el6_7.7 will be an update
---> Package java-1.8.0-openjdk-headless.x86_64 1:1.8.0.71-1.b15.el6_7 will be i                                                nstalled
--> Running transaction check
---> Package glibc-devel.x86_64 0:2.12-1.166.el6_7.3 will be updated
---> Package glibc-devel.x86_64 0:2.12-1.166.el6_7.7 will be an update
---> Package glibc-headers.x86_64 0:2.12-1.166.el6_7.3 will be updated
---> Package glibc-headers.x86_64 0:2.12-1.166.el6_7.7 will be an update
--> Finished Dependency Resolution
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:

         1. You have an upgrade for openssl which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of openssl of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude openssl.otherarch ... this should give you an error
            message showing the root cause of the problem.

         2. You have multiple architectures of openssl installed, but
            yum can only see an upgrade for one of those arcitectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.

         3. You have duplicate versions of openssl installed already.
            You can use "yum check" to get yum show these errors.

       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).

       Protected multilib versions: openssl-1.0.1e-42.el6_7.4.x86_64 != openssl-                                                1.0.1e-42.el6_7.1.i686
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json trim@0.0.1 No repository field.
npm WARN prefer global forever@0.15.1 should be installed with -g
```

**Comment by LordRalex** [comment]
Okay, that explains it. Your system has an old version of nodejs, to which does not support our modules apparently.

I am going to be releasing an update to PufferPanel in the coming days to resolve a deployment issue with Scales, and I will add an additional fix to help prevent these problems in the future.

To resolve your problem, what you can do is the following:

```
nodeURL=https://nodejs.org/dist/v4.2.4/node-v4.2.4-linux-x64.tar.gz
cd /srv/scales
curl -o node.tar.gz ${nodeURL}
tar -xf node.tar.gz
rm -f node.tar.gz
mv node-* node
./scales node_install
```

**Comment by SysVoid** [comment]
```
Using packaged node
Starting Scales
[2016-03-03 04:23:06] [INFO] + ========================================== +
[2016-03-03 04:23:06] [INFO] | Scales logs all information, (inc. errors) |
[2016-03-03 04:23:06] [INFO] | into the logs/ directory. Please check     |
[2016-03-03 04:23:06] [INFO] | there before asking for help with bugs.    |
[2016-03-03 04:23:06] [INFO] |                                            |
[2016-03-03 04:23:06] [INFO] | Submit bug reports at the following link:  |
[2016-03-03 04:23:06] [INFO] | https://github.com/PufferPanel/Scales      |
[2016-03-03 04:23:06] [INFO] + ========================================== +
[2016-03-03 04:23:07] [ERROR] uncaughtException: Module did not self-register.
[2016-03-03 04:23:07] [ERROR] Unhandled exception occurred
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/srv/scales/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

**Comment by LordRalex** [comment]
Please run the following command again:
./scales node_install
