### ISSUE TITLE
On starting .. 

### ISSUE THREAD

**Issue by Noahyup** [PufferPanel/Scales#84]
[2016-03-17 17:37:11] [INFO] | Scales logs all information, (inc. errors) |
[2016-03-17 17:37:11] [INFO] | into the logs/ directory. Please check     |
[2016-03-17 17:37:11] [INFO] | there before asking for help with bugs.    |
[2016-03-17 17:37:11] [INFO] |                                            |
[2016-03-17 17:37:11] [INFO] | Submit bug reports at the following link:  |
[2016-03-17 17:37:11] [INFO] | https://github.com/PufferPanel/Scales      |
[2016-03-17 17:37:11] [INFO] + ========================================== +
[2016-03-17 17:37:12] [ERROR] uncaughtException: listen EADDRINUSE 0.0.0.0:5656
[2016-03-17 17:37:12] [ERROR] Unhandled exception occurred
Error: listen EADDRINUSE 0.0.0.0:5656
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1238:14)
    at listen (net.js:1274:10)
    at net.js:1383:9
    at doNTCallback3 (node.js:452:9)
    at process._tickDomainCallback (node.js:399:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by puffrfish** [comment]
This usually means there is already a Scales process running. You can run `ps aux` to see the currently running processes and their process IDs, and then use `kill 1234` (replacing 1234 with the process ID) to stop any running Scales processes.

After that you should be able to start it up using `./scales start` and if you wish to stop it in the future, `./scales stop`.

In the future, issues such as this should be posted to the [community forums](https://community.pufferpanel.com). Thanks!
