### ISSUE TITLE
No plugin specified results in failure

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/Scales#9]
20:57:05 - verbose: An exception occured trying to process adding a new server. meta=TypeError: Cannot read property 'joined' of undefined
    at new Scales (/srv/Scales/lib/process.js:36:40)
    at initalize (/srv/Scales/lib/initalize.js:51:23)
    at Server.rest.put.server (/srv/Scales/lib/interfaces/restify.js:140:4)
    at next (/srv/Scales/node_modules/restify/lib/server.js:745:30)
    at f (/srv/Scales/node_modules/restify/node_modules/once/once.js:17:25)
    at Server.restifyCORSSimple (/srv/Scales/node_modules/restify/lib/plugins/cors.js:95:13)
    at next (/srv/Scales/node_modules/restify/lib/server.js:745:30)
    at f (/srv/Scales/node_modules/restify/node_modules/once/once.js:17:25)
    at Server.parseQueryString (/srv/Scales/node_modules/restify/lib/plugins/query.js:39:17)
    at next (/srv/Scales/node_modules/restify/lib/server.js:745:30)

**Comment by LordRalex** [comment]
https://github.com/PufferPanel/PufferPanel/issues/497

**Comment by DaneEveritt** [comment]
Haven't been able to reproduce this again, so closing.
