### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by tomisanhues2** [PufferPanel/Scales#91]
I have a problem when I start scales... 
`[ERROR] uncaughtException: Module version mismatch. Expected 46, got 14.
[2016-06-14 20:13:40] [ERROR] Unhandled exception occurred
Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/srv/scales/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
`

**Comment by nishuzumi** [comment]
i have some problem like yours
